name: hol-devoxxbe
services:
  
  postgres:
    hostname: postgres
    image: quay.io/debezium/example-postgres:2.7.3.Final
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./infra/postgres/public_inventory.sql:/docker-entrypoint-initdb.d/public_inventory.sql
      - ./infra/postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
    networks:
      - my-network

  opensearch-node1:
    hostname: opensearch-node1
    image: opensearchproject/opensearch:1.3.19
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - my-network

  jobmanager:
    image: flink:1.19.1-scala_2.12-java17
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./infra/flink/libs/flink-sql-connector-postgres-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-2.3.0.jar
      - ./infra/flink/libs/flink-sql-connector-opensearch-1.2.0-1.19.jar:/opt/flink/lib/flink-sql-connector-opensearch-1.2.0-1.19.jar
      # - ./array-agg-udf/target/array-agg-0.1.jar:/opt/flink/lib/array-agg-0.1.jar
      - ./infra/flink/udfs/http-fetcher-0.1.jar:/opt/flink/lib/http-fetcher-0.1.jar
    networks:
      - my-network
  taskmanager:
    image: flink:1.19.1-scala_2.12-java17
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
    volumes:
      - ./infra/flink/libs/flink-sql-connector-postgres-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-2.3.0.jar
      - ./infra/flink/libs/flink-sql-connector-opensearch-1.2.0-1.19.jar:/opt/flink/lib/flink-sql-connector-opensearch-1.2.0-1.19.jar
      # - ./array-agg-udf/target/array-agg-0.1.jar:/opt/flink/lib/array-agg-0.1.jar
      - ./infra/flink/udfs/http-fetcher-0.1.jar:/opt/flink/lib/http-fetcher-0.1.jar
    networks:
      - my-network
  sql-client:
    image: flink:1.19.1-scala_2.12-java17
    command: tail -f /dev/null
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      - ./infra/flink/libs/flink-sql-connector-postgres-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-2.3.0.jar
      - ./infra/flink/libs/flink-sql-connector-opensearch-1.2.0-1.19.jar:/opt/flink/lib/flink-sql-connector-opensearch-1.2.0-1.19.jar
      # - ./array-agg-udf/target/array-agg-0.1.jar:/opt/flink/lib/array-agg-0.1.jar
      - ./infra/flink/udfs/http-fetcher-0.1.jar:/opt/flink/lib/http-fetcher-0.1.jar
    networks:
      - my-network

  model-serving-app:
    hostname: model-serving-app
    image: hpgrahsl/hol-devoxxbe-model-serving-app:1.0.0
    ports:
      - "9090:8080"
    networks:
      - my-network

  review-app:
    hostname: review-app
    image: hpgrahsl/hol-devoxxbe-review-app:1.0.1
    ports:
      - "9091:8080"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    name: hol-devoxxbe-network
